baseURL = "https://www.brainstormer.online"
languageCode = "en-us"
title = "Brainstormer"

enableEmoji = true
enableRobotsTXT = true

[[menu.main]]
  name = "About"
  url = "/about"

[[menu.main]]
  name = "Blog"
  url = "/blog"