baseURL = "https://www.brainstormer.online"
languageCode = "en-us"
title = "Brainstormer"

enableEmoji = true
enableRobotsTXT = true

[[menu.main]]
  name = "About"
  url = "/about"
    [menu.main.params]
    class = "bg-white"

[[menu.main]]
  name = "Blog"
  url = "/blog"
    [menu.main.params]
    class = "bg-white" 

[[menu.main]]
  name = "Buy me a coffee"
  url = "/buy-me-a-coffee"
  pre = "<i>☕</i>"
  [menu.main.params]
    class = "bg-yellowy" 

[params]
    Description = "Easy facilitation of online brainstorming sessions"
    Image = "/images/some_image.png"
    sitename = "Brainstormer"

[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    weight = 1
     