baseURL = "https://lonekp.github.io/brainstormer-landing-page/"
languageCode = "en-us"
title = "Brainstormer.online"

enableEmoji = true

[[menu.main]]
  name = "About"
  url = "/about"

[[menu.main]]
  name = "Blog"
  url = "/blog"