baseURL = "https://www.blog.brainstormer.online"
languageCode = "en-us"
title = "Brainstormer | Blog "

enableEmoji = true
enableRobotsTXT = true

[params]
    Description = "Easy facilitation of online brainstorming sessions"
    Image = "/images/some_image.png"
    sitename = "Brainstormer | Blog"

[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    weight = 1
     